### ISSUE TITLE
having some build issue

### ISSUE THREAD

**Issue by kapadiyajay** [aws-samples/aws-iot-core-for-amazon-sidewalk-sample-app#51]
hi i have some issue while executing this command during test sidewalk with nodic52840DK : 

**py -m pip install -r requirements.txt**

hear are logs for debugging:

`(sample-app-env) C:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk>python -m pip install -r requirements.txt
Processing c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\edgedeviceprovisioning\tools\botocore-1.29.83-py3-none-any.whl (from -r requirements.txt (line 5))
Processing c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\edgedeviceprovisioning\tools\boto3-1.26.83-py3-none-any.whl (from -r requirements.txt (line 6))
Processing c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\edgedeviceprovisioning\tools\awscli-1.27.83-py3-none-any.whl (from -r requirements.txt (line 7))
Collecting colorama>=0.4 (from -r requirements.txt (line 1))
  Using cached colorama-0.4.6-py2.py3-none-any.whl (25 kB)
Collecting pyyaml (from -r requirements.txt (line 2))
  Obtaining dependency information for pyyaml from https://files.pythonhosted.org/packages/b3/34/65bb4b2d7908044963ebf614fe0fdb080773fc7030d7e39c8d3eddcd4257/PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata
  Using cached PyYAML-6.0.1-cp311-cp311-win_amd64.whl.metadata (2.1 kB)
Collecting requests~=2.25.1 (from -r requirements.txt (line 3))
  Using cached requests-2.25.1-py2.py3-none-any.whl (61 kB)
Collecting intelhex (from -r requirements.txt (line 4))
  Using cached intelhex-2.3.0-py2.py3-none-any.whl (50 kB)
Collecting chardet<5,>=3.0.2 (from requests~=2.25.1->-r requirements.txt (line 3))
  Using cached chardet-4.0.0-py2.py3-none-any.whl (178 kB)
Collecting idna<3,>=2.5 (from requests~=2.25.1->-r requirements.txt (line 3))
  Using cached idna-2.10-py2.py3-none-any.whl (58 kB)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\lib\site-packages (from requests~=2.25.1->-r requirements.txt (line 3)) (1.26.16)
Collecting certifi>=2017.4.17 (from requests~=2.25.1->-r requirements.txt (line 3))
  Obtaining dependency information for certifi>=2017.4.17 from https://files.pythonhosted.org/packages/4c/dd/2234eab22353ffc7d94e8d13177aaa050113286e93e7b40eae01fbf7c3d9/certifi-2023.7.22-py3-none-any.whl.metadata
  Using cached certifi-2023.7.22-py3-none-any.whl.metadata (2.2 kB)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\lib\site-packages (from botocore==1.29.83->-r requirements.txt (line 5)) (1.0.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\lib\site-packages (from botocore==1.29.83->-r requirements.txt (line 5)) (2.8.2)
Requirement already satisfied: s3transfer<0.7.0,>=0.6.0 in c:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\lib\site-packages (from boto3==1.26.83->-r requirements.txt (line 6)) (0.6.2)
Collecting docutils<0.17,>=0.10 (from awscli==1.27.83->-r requirements.txt (line 7))
  Using cached docutils-0.16-py2.py3-none-any.whl (548 kB)
Collecting pyyaml (from -r requirements.txt (line 2))
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [68 lines of output]
      C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\ncs\v2.3.0\sidewalk\tools\aws-iot-core-for-sidewalk\sample-app-env\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\dist.py", line 1233, in run_command
          super().run_command(command)
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 319, in run
          self.find_sources()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 327, in find_sources
          mm.run()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 549, in run
          self.add_defaults()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 587, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\command\sdist.py", line 113, in add_defaults
          super().add_defaults()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\SLPL-J\AppData\Local\Temp\pip-build-env-ox9g5hlr\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

**Comment by RobertGalatNordic** [comment]
The same issue on Ubuntu 22.04

**Comment by jerlegoman** [comment]
This issue is due to an issue with the requirements.txt file
modify,
`pyyaml`
to
`pyyaml==5.3.1`
It seems that the newest version of pyyaml has some sort of issue. 5.3.1 Works
