### ISSUE TITLE
Cant build sidewalk-sample-app because of cython upgrade??

### ISSUE THREAD

**Issue by mbalsam** [aws-samples/aws-iot-core-for-amazon-sidewalk-sample-app#54]
When i try to follow these steps 

python -m pip install --user virtualenv
python -m venv sample-app-env
sample-app-env\Scripts\activate.bat
python -m pip install --upgrade pip
python -m pip install -r requirements.txt

I get this stack trace below.  

I'm a python nube but, I've read that Cython has recently been upgraded to 3.0. could this be the reason?.

Last thing it output was 

AttributeError: cython_sources

Please help.  Just want to try to use sidewalk.

PS C:\Users\username
/\aws-iot-core-for-amazon-sidewalk-sample-app> python -m pip install -r requirements.txt
Processing c:\users\username\aws-iot-core-for-amazon-sidewalk-sample-app\edgedeviceprovisioning\tools\botocore-1.29.83-py3-none-any.whl (from -r requirements.txt (line 5))
Processing c:\users\username\aws-iot-core-for-amazon-sidewalk-sample-app\edgedeviceprovisioning\tools\boto3-1.26.83-py3-none-any.whl (from -r requirements.txt (line 6))
Processing c:\users\username\aws-iot-core-for-amazon-sidewalk-sample-app\edgedeviceprovisioning\tools\awscli-1.27.83-py3-none-any.whl (from -r requirements.txt (line 7))
Requirement already satisfied: colorama>=0.4 in c:\users\username\appdata\local\packages\pythonsoftwarefoundation.python.3.11_qbz5n2kfra8p0\localcache\local-packages\python311\site-packages (from -r requirements.txt (line 1)) (0.4.4)
Collecting pyyaml==5.4.1 (from -r requirements.txt (line 2))
  Using cached PyYAML-5.4.1.tar.gz (175 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib3\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib3\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib3\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 271, in <module>
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 551, in run
          self.add_defaults()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 589, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\command\sdist.py", line 112, in add_defaults
          super().add_defaults()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 201, in get_source_files
        File "C:\Users\username\AppData\Local\Temp\pip-build-env-mo144gwc\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by mbalsam** [comment]
Im following the instructions here - https://docs.rakwireless.com/Product-Categories/WisBlock/RAK4631/Sidewalk/#aws-setup

I was able to get past the AttributeError: cython_sources with hints from https://github.com/yaml/pyyaml/issues/601

$ pip install "cython<3.0.0" wheel
$ pip install "pyyaml==5.4.1" --no-build-isolation
$ pip install -r requirements.txt

Next, when i do 
$ python -m pip install pyjwt -t .\ApplicationServerDeployment\lambda\authLibs

I get "ERROR: Can not combine '--user' and '--target'"

This is fixed by adding --no-user

As in: 
python -m pip install pyjwt -t .\ApplicationServerDeployment\lambda\authLibs --no-user

The next step in the instructions is to run 

python3 env_check

Then i get these errors 

[CHECK] BOTO3 VERSION
[ERROR]         FAIL! the installed version of boto3 doesn't support Sidewalk AWS APIs. Did you install requirements.txt?
[CHECK] SIMPLICITY COMMANDER PRESENCE
[ERROR]         FAIL! Unable to find Simplicity Commander! Please install https://community.silabs.com/s/article/simplicity-commander and add the path to config.yaml

adding the Simplicity Commander fixed one of the problems   https://community.silabs.com/s/article/simplicity-commander

But the BOTO3 issues remains

**Comment by mbalsam** [comment]
Everything works now.   i had created the config file as config.txt  which was a problem. 

In requirements, I also changed
    pyyaml
to 
    pyyaml==5.3.1

**Comment by mbalsam** [comment]
finished.
